### ISSUE TITLE
Razliciti brojevi u grafovima

### ISSUE THREAD

**Issue by fpetric** [ppalasek/covid_plots_croatia#1]
Bok @ppalasek, 

pratim ove tvoje crckarije, zadnjih par dana se pojavljuju neki razliciti brojevi a to nisam ranije primjetio. Na danasnjem primjeru, graf broja slucajeva za RH, broj slucajeva na 100k je 344, a period udvostrucavanja 10.15+-0.6 a onda na ovom grafu gdje su i hospitalizacije i umrli se pojavi broj slucajeva na 100k da je 343 a period udvostrucavanja 10.55+-1.93.

**Comment by ppalasek** [comment]
Bok @fpetric :)

Istina! Nije namjerno, ups. Neki dan sam promijenio da se u ovim grafovima po regijama krivulja fita na zadnjih 14 točaka (prije je bilo 7), a nisam promijenio na ovom drugom grafu, tamo je i dalje 7. Možeš vidjeti razliku u duljini aproksimacijske krivulje...  Ne znam jel bolje da vratim na 7 dana svugdje ili na 14. Kaj predlažeš?

BTW, gledao sam i da fitam i sigmoid i gompertz krivulje pa da sve prikažem na istom mjestu, uz ovu eksponencijalnu. Ako nađem vremena da sve ispoliram da ok izgleda dodam i taj prikaz.

Edit. A ovo sutra promijenim da bude konzistentno u svim grafovima. Tenks na komentaru!

**Comment by fpetric** [comment]
Cini mi se s obzirom na dinamiku (osobito nekonzistentnost testiranja) da je bolje (informativnije) 7 dana, jer imas dosta visok threshold za prikaz te estimacije i cini mi se da s 14 dana neces cesto dobit da se to fita kako spada i prikaze.

**Comment by ppalasek** [comment]
Je, vratio sam danas na 7 dana pa više nema razlike. Možda spustim threshold na 0.9 sutra, namjerno je jako visoko da ne prikazuje baš totalne gluposti :D
